# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on: [push]
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy to Fly
        run: |
          max_retries=3
          retry_delay=5

          for i in $(seq 1 $max_retries); do
            echo "Attempt $i to deploy..."
            
            # Check machine status
            if flyctl status | grep -q "running"; then
              echo "Stopping existing machine..."
              flyctl machine stop
              sleep $retry_delay
            fi
            
            # Attempt to deploy
            if flyctl deploy; then
              echo "Deployment successful!"
              exit 0
            else
              echo "Deployment failed. Retrying in $retry_delay seconds..."
              sleep $retry_delay
            fi
          done

          echo "Deployment failed after $max_retries attempts."
          exit 1
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
